export const ADD_FAVORITE = "ADD_FAVORITE"
export const REMOVE_FAVORITE = "REMOVE_FAVORITE"
export const TOGGLE_DARKTHEME = "TOGGLE_DARKTHEME";
export const ADD_DARKTHEME = "ADD_DARKTHEME";
export const REMOVE_DARKTHEME = "REMOVE_DARKTHEME";